name: Build DataTest example
on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/build_datatest.yml
      - 'template/**'
      - 'layer/**'
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TARGET_TYPE:  STM32H735G-DK
  TARGET_BOARD: STM32H735G-DK
  TARGET_BSP:   STM32H735G-DK_BSP
# TARGET_LAYER: $SolutionDir()$/../../../.ci/Board/Board.clayer.yml

jobs:
  Build:                                # Install tools, build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        solution: [
          {name: FileSystem, dir: SDS_FileSystem, sdsio_layer_file: $SolutionDir()\$/sdsio/filesystem/sdsio_fs.clayer.yml   },
          {name: Network,    dir: SDS_Network   , sdsio_layer_file: $SolutionDir()\$/sdsio/network/sdsio_network.clayer.yml },
          {name: USB,        dir: SDS_USB       , sdsio_layer_file: $SolutionDir()\$/sdsio/usb/sdsio_usb.clayer.yml         }
        ]

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: "./.ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Initialize CMSIS pack root folder
        run: |
          cpackget init https://www.keil.com/pack/index.pidx
          cpackget update-index

      - name: Install required publicly released CMSIS packs
        run: |
          cpackget add Keil.MDK-Middleware -a
          cpackget add MDK-Packs.IoT_Socket -a
          cpackget add ARM.CMSIS-Driver_STM32 -a
          cpackget add Keil.STM32H7xx_DFP -a
          cpackget add Keil.STM32H735G-DK_BSP -a

      - name: Use repository version of this CMSIS pack instead of released one
        run: |
          cpackget add ./ARM.SDS.pdsc

      - name: Copy template to ${{ matrix.solution.dir }} folder
        run: |
          mkdir -p ./${{ matrix.solution.dir }}
          cp -r ./template/. ./${{ matrix.solution.dir }}/

      - name: Copy first ${{ env.TARGET_BOARD }} layer to ./${{ matrix.solution.dir }}/Board/${{ env.TARGET_BOARD }}
        run: |
          mkdir -p ./${{ matrix.solution.dir }}/Board/$TARGET_BOARD
          cp -r "$(find /home/runner/.cache/arm/packs/Keil/$TARGET_BSP -type f -name "Board.clayer.yml" -exec dirname {} \; | head -n 1)"/* ./${{ matrix.solution.dir }}/Board/$TARGET_BOARD/
          ls -a -R ./${{ matrix.solution.dir }}/Board/$TARGET_BOARD/

      - name: Copy layer/sdsio to ./${{ matrix.solution.dir }}/sdsio
        run: |
          mkdir -p ./${{ matrix.solution.dir }}/sdsio
          cp -r ./layer/sdsio/* ./${{ matrix.solution.dir }}/sdsio/
          ls -a -R ./${{ matrix.solution.dir }}/sdsio/

      - name: Setup board layer
        working-directory: ./${{ matrix.solution.dir }}
        shell: bash
        run: |
          set -x

          sed -i "/- type: \\\${Name}/c\    - type: ${TARGET_TYPE}\\n      board: ${TARGET_BOARD}\\n      variables:\\n        - Board-Layer: \\$SolutionDir()\\\\\\$/Board/${TARGET_BOARD}/Board.clayer.yml\\n        - SDSIO-Layer: \\\${{ matrix.solution.sdsio_layer_file }}" SDS.csolution.yml

          cat ./SDS.csolution.yml

          # target_board="    - type: ${TARGET_TYPE}
          #   board: ${TARGET_BOARD}
          #   variables:
          #     - Board-Layer: \$SolutionDir()\\\$/Board/${TARGET_BOARD}/Board.clayer.yml
          #     - SDSIO-Layer: \${{ matrix.solution.sdsio_layer_file }}
          #   "

          # echo $target_board

          # sed -i "/- type: \\\${Name}/c\\$target_board" SDS.csolution.yml

#         sed -i '/- type: \${Name}/c\    - type: ${TARGET_TYPE}\n      board: ${TARGET_BOARD}\n      variables:\n        - Board-Layer: $SolutionDir()\\$/Board/${TARGET_BOARD}/Board.clayer.yml\n        - SDSIO-Layer: ${{ matrix.solution.sdsio_layer_file }}\n\n' SDS.csolution.yml
#         sed -i '/- type: ${name}/{s/.*/    - type: ${TARGET_TYPE}/a\n      board: ${TARGET_BOARD}\n      variables:\n        - Board-Layer: $SolutionDir()\\$/Board/${TARGET_BOARD}/Board.clayer.yml\n        - SDSIO-Layer: ${{ matrix.solution.sdsio_layer_file }}}' SDS.csolution.yml
#         sed -i "s|- type: ${Name}|&\n    - type: $TARGET_TYPE\n      board: $TARGET_BOARD\n      variables:\n      - Board-Layer: $SolutionDir()$/Board/$TARGET_BOARD/Board.clayer.yml\n      - SDSIO-Layer: ${{ matrix.solution.sdsio_layer_file }}\n" ./${{ matrix.solution.dir }}.csolution.yml

      - name: Build ./${{ matrix.solution.dir }}/DataTest example
        working-directory: ./${{ matrix.solution.dir }}
        run: |
          cbuild ./SDS.csolution.yml --packs --update-rte --toolchain AC6
